### ISSUE TITLE
Avoid residual redirection in xfce-migrate-to-gl

### ISSUE THREAD

**Issue by Tamaranch** [ochosi/xfce-helpers#14]
Hi,

You could add
```sh
sed -Ei 's|(https://gitlab\.xfce\.org/.*)/$|\1.git|' .git/config
```
(or something like that) to avoid a residual redirection after applying the script.

**Comment by ochosi** [comment]
I'm on my phone so I can't test your code but could you explain what you mean with 'residual redirection'?

**Comment by Tamaranch** [comment]
If you clone e.g. `xfce4-session` by
```
git clone https://git.xfce.org/xfce/xfce4-session/
```
you have
```
  url = https://git.xfce.org/xfce/xfce4-session/
```
in your `.git/config` file.

Then, applying your script, you obtain
```
  url = https://gitlab.xfce.org/xfce/xfce4-session/
```
But the real gitlab url for cloning should be
```
  url = https://gitlab.xfce.org/xfce/xfce4-session.git
```
So, when you `git pull`, you obtain
```
warning: redirecting to https://gitlab.xfce.org/xfce/xfce4-session.git/
```
This is the "residual redirection" (probably not a good term :smile:) that my `sed` command above avoids.

**Comment by ochosi** [comment]
Oh right, now I understand :)
I only have ssh URLs that's why I didn't notice this redirect. Wanna make this a pull-request?

**Comment by Tamaranch** [comment]
Any problem with the pull-request?

**Comment by ochosi** [comment]
Not at all, only that I didn't receive a notification for it :)
Thanks for the reminder!
