### ISSUE TITLE
Dynamically generate the language list

### ISSUE THREAD

**Issue by Skunnyk** [ochosi/xfce-helpers#2]
Dynamically generate the language list.

I have a custom script for this step which extract language list from the .po:

> echo -n "$(grep '^"Language-Team:' po/$lang.po | grep -Po '(?<=: ).*' | grep -Po '^.*?(?= \(http)')"

This way no need to have an hardcoded list.

**Comment by andreldm** [comment]
I don't know if the hardcoded list is to blame, but when releasing tumbler 0.2.5, thunar-volman 0.9.3 and xfce4-appfinder 4.13.4 I noticed some locales were not reported. To reproduce it's quite easy, just checkout to the commit before those releases and remove the newer tags.

My [hacky script](https://gist.github.com/andreldm/2e491f1e701425c703c4400f0e88e957) works fine, but I guess Skunnyk's approach is more elegant and reliable (unless Transifex screws po files).

**Comment by ochosi** [comment]
PR please :)
